### ISSUE TITLE
deepmerge dependency causes a warning

### ISSUE THREAD

**Issue by ebussieres** [denniske/ngx-translate-multi-http-loader#17]
[1] Warning: ...\node_modules\ngx-translate-multi-http-loader\dist\multi-http-loader.js depends on 'deepmerge'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by ojacquemart** [comment]
You should check this page of the build section from the angular documentation: https://angular.io/guide/build#configuring-commonjs-dependencies, to allow "lodash" as a commonJS dependency.

**Comment by ebussieres** [comment]
I know that I can allow this dependency in order to remove the warning message.

The documentation says this : 


> It is recommended that you avoid depending on CommonJS modules in your Angular applications. Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use [ECMAScript modules](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Statements/import) in your entire application. For more information, see [How CommonJS is making your bundles larger](https://web.dev/commonjs-larger-bundles).

**Comment by acuevas91** [comment]
Is any update on that? I do not know if could be possible to replace deepmerge lib by a esm one. Thanks!

**Comment by rbalet** [comment]
@ebussieres, @acuevas91  Done on the [latest v9.1.0 version](https://github.com/rbalet/ngx-translate-multi-http-loader/releases/tag/v9.1.2)!

Since npm `v^8.19.0` does now  auto import peerDependencies, I didn't added in the `README.md` file, but if you wish you could also run an `npm i deepmerge-ts` in your project.

@ojacquemart FYI, the library isn't using `loadash` since it's way to heavy, but [deepmerge-ts](https://www.npmjs.com/package/deepmerge-ts), which should be faster :)

Let me know if it works the way it should.
