### ISSUE TITLE
JSON not loaded

### ISSUE THREAD

**Issue by EricSch** [denniske/ngx-translate-multi-http-loader#19]
Hi,

Before the V9 change, i could define with the prefix and suffix to load the two files: **de.json** and **de.shared.json**. Both were in the same folder. 

Is this still possible or do I have to move now a file into a subfolder?

Thanks

**Comment by rbalet** [comment]
Hi @EricSch ,

Thx for reporting that issue.

I though suffix & prefix weren't used anymore, because this library only support `.json` file type.  
But didn't thought of this scenario...

Well, this is now fixed over on the latest [v9.0.1](https://github.com/rbalet/ngx-translate-multi-http-loader/releases/tag/v9.0.1)  --> `npm i ngx-translate-multi-http-loader@latest`

I made the `suffix` being optional and by default is now `.json`, so you can remove this part from your code ;).

Here on how to implement the new logic (but shouldn't break anything ;)
https://github.com/rbalet/ngx-translate-multi-http-loader#custom-suffix

Let me know if it worked.

Closing this issue as completed
